# Generated by Django 3.1.7 on 2021-08-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becarios',
            name='posta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='postas.postas'),
        ),
        migrations.AlterField(
            model_name='postas',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postas',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
