# Generated by Django 3.1.7 on 2021-08-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0002_auto_20210807_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='becarios',
            name='turno',
            field=models.CharField(blank=True, choices=[('M', 'MAÑANA'), ('T', 'TARDE'), ('N', 'NOCHE'), ('MT', '12 HORAS')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='becarios',
            name='carga_horaria',
            field=models.CharField(blank=True, choices=[('LAV', 'LUNES A VIERNES'), ('FIN', 'FINES DE SEMANA'), ('LAL', 'LUNES A LUNES'), ('NOC', 'NOCHE')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='becarios',
            name='tarea',
            field=models.CharField(blank=True, choices=[('PRE', 'PRE-VACUNACION'), ('TRI', 'TRIANGE'), ('LIM', 'LIMPIEZA'), ('ADM', 'ADMINISTRATIVO/A'), ('COR', 'COORDINADOR/A'), ('NOC', 'NOCHE'), ('VAC', 'VACUNADOR/A')], max_length=5, null=True),
        ),
    ]
