# Generated by Django 3.1.7 on 2021-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0003_auto_20210807_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
