# Generated by Django 3.1.7 on 2021-08-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0004_auto_20210807_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='becarios',
            name='region',
            field=models.BooleanField(default=False),
        ),
    ]
