# Generated by Django 3.1.7 on 2021-08-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0005_becarios_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('P', 'PRESENTE'), ('A', 'AUSENTE')], max_length=5, null=True)),
                ('certificado', models.BooleanField(default=False)),
                ('becario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='postas.becarios')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
