# Generated by Django 3.1.7 on 2021-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0006_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='becario',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(blank=True, choices=[('P', 'PRESENTE'), ('A', 'AUSENTE')], max_length=1, null=True),
        ),
    ]
