# Generated by Django 3.1.7 on 2021-08-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0009_auto_20210808_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
