# Generated by Django 3.1.7 on 2021-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0010_asistencia_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becarios',
            name='tarea',
            field=models.CharField(blank=True, choices=[('PRE', 'PRE-VACUNACION'), ('TRI', 'TRIANGE'), ('LIM', 'LIMPIEZA'), ('ADM', 'ADMINISTRATIVO/A'), ('COR', 'COORDINADOR/A'), ('NOC', 'NOCHE'), ('VAC', 'VACUNADOR/A'), ('LOG', 'LOGISTICA')], max_length=5, null=True),
        ),
    ]
