# Generated by Django 3.1.7 on 2021-08-17 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0011_auto_20210809_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='conteo_de_vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('turnera', models.IntegerField(blank=True, null=True)),
                ('faltas', models.IntegerField(blank=True, null=True)),
                ('espontanea', models.IntegerField(blank=True, null=True)),
                ('primera_dosis', models.IntegerField(blank=True, null=True)),
                ('segunda_dosis', models.IntegerField(blank=True, null=True)),
                ('posta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postas.postas')),
            ],
            options={
                'verbose_name': 'Conteo',
                'verbose_name_plural': 'Conteo',
            },
        ),
    ]
