# Generated by Django 3.1.7 on 2021-08-17 22:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0013_auto_20210817_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteo_de_vacunas',
            name='turnera',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/sgpami.ar/sgpami/media/turnera'), upload_to=''),
        ),
    ]
