# Generated by Django 3.1.7 on 2021-08-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0014_auto_20210817_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteo_de_vacunas',
            name='total_vacunados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
