# Generated by Django 3.1.7 on 2021-08-19 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0015_conteo_de_vacunas_total_vacunados'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_de_vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('laboratorio', models.CharField(blank=True, choices=[('A', 'ASTRASENECA'), ('S', 'SPUNK V')], max_length=2, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('1', 'PRIMERA DOSIS'), ('2', 'SEGUNDA DOSIS'), ('3', 'NO APLICA')], max_length=2, null=True)),
                ('formato', models.CharField(blank=True, choices=[('M', 'MODOSIS'), ('D', '10')], max_length=2, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('posta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postas.postas')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Stock de Vacunas',
            },
        ),
    ]
