# Generated by Django 3.1.7 on 2021-08-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0016_stock_de_vacunas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteo_de_vacunas',
            options={'verbose_name': 'Conteo de Turnos diarios', 'verbose_name_plural': 'Conteo'},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='organizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='posta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
