# Generated by Django 3.1.7 on 2021-08-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postas', '0017_auto_20210819_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='becarios',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conteo_de_vacunas',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock_de_vacunas',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
