# Generated by Django 3.1.7 on 2021-06-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agenda'},
        ),
        migrations.AddField(
            model_name='agenda',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='horas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='lugar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
