# Generated by Django 3.1.7 on 2021-06-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20210606_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horas',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
