# Generated by Django 3.1.7 on 2021-06-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20210607_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
