# Generated by Django 3.1.7 on 2021-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agenda_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='organismo',
            field=models.CharField(choices=[('SUB', 'Subsecreatria de DDHH'), ('PAM', 'PAMI'), ('COE', 'Consejo Escolar'), ('ANS', 'ANSES'), ('ACU', 'ACUMAR'), ('REN', 'RENAPER'), ('MIG', 'Migraciones'), ('IOM', 'IOMA'), ('VAC', 'Vacunate'), ('MER', 'Mercado')], max_length=3),
        ),
    ]
