# Generated by Django 3.1.7 on 2021-08-31 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0021_auto_20210614_1414'),
        ('agenda', '0007_agenda_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prestadores.localidad'),
        ),
    ]
