# Generated by Django 3.1.7 on 2021-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_agenda_localidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='id',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='lugar',
            field=models.CharField(blank=True, default='A DEFINIR', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
