# Generated by Django 3.1.7 on 2021-11-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_agenda_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
