# Generated by Django 3.1.7 on 2021-11-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0040_cuadricula_caso_de_gestion'),
        ('agenda', '0014_agenda_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='territorio.organizacion'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='responsable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
