# Generated by Django 3.1.7 on 2021-11-18 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0042_auto_20211118_1519'),
        ('agenda', '0015_auto_20211118_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='territorio.compañerxs'),
        ),
    ]
