# Generated by Django 3.1.7 on 2021-06-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0008_auto_20210608_1517'),
        ('prestadores', '0021_auto_20210614_1414'),
        ('territorio', '0002_auto_20210614_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jefe', models.CharField(blank=True, max_length=50, null=True)),
                ('sede', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prestadores.localidad')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prestadores.municipio')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos_de_gestion.organismo')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
    ]
