# Generated by Django 3.1.7 on 2021-06-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0003_instituciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.CharField(blank=True, max_length=5, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('menores', models.CharField(blank=True, max_length=5, null=True)),
                ('mayores', models.CharField(blank=True, max_length=5, null=True)),
                ('inscriptx_vacuna', models.BooleanField()),
                ('desea_inscribirse', models.BooleanField()),
                ('cobran_prestaciones_de_anses_correctamente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Cuadricula',
                'verbose_name_plural': 'Cuadriculas',
            },
        ),
    ]
