# Generated by Django 3.1.7 on 2021-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0005_auto_20210615_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadricula',
            name='cobertura_de_salud',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuadricula',
            name='inconveniente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuadricula',
            name='prestador',
            field=models.CharField(blank=True, choices=[('SPUB', 'Sulud Publica'), ('SPRI', 'Sulud Privada'), ('PAMI', 'PAMI'), ('IOMA', 'IOMA'), ('INCL', 'INCLUIR'), ('OTRA', 'OTRA')], max_length=4, null=True),
        ),
    ]
