# Generated by Django 3.1.7 on 2021-06-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0012_auto_20210615_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadricula',
            name='DNI',
            field=models.BooleanField(blank=True, help_text='Tiene actualmente DNI', null=True),
        ),
        migrations.AlterField(
            model_name='cuadricula',
            name='prestacion_alinentaria',
            field=models.BooleanField(blank=True, help_text='Reciben prestacion alimentaria o asisten a algun comedor o merendero', null=True),
        ),
    ]
