# Generated by Django 3.1.7 on 2021-06-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0013_auto_20210615_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuadricula',
            options={'verbose_name': 'Encuestado', 'verbose_name_plural': 'Cuadriculas'},
        ),
    ]
