# Generated by Django 3.1.7 on 2021-06-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0015_auto_20210615_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadricula',
            name='mayores',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cuantos menores viven en el hogar'),
        ),
        migrations.AlterField(
            model_name='cuadricula',
            name='menores',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cuantos menores viven en el hogar'),
        ),
    ]
