# Generated by Django 3.1.7 on 2021-06-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0016_auto_20210615_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadricula',
            name='inscriptx_vacuna',
            field=models.BooleanField(blank=True, null=True, verbose_name='Esta Incriptx a la vacuna contra el COVID-19'),
        ),
        migrations.AlterField(
            model_name='cuadricula',
            name='mayores',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cuantos mayores viven en el hogar'),
        ),
    ]
