# Generated by Django 3.1.7 on 2021-06-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0017_auto_20210615_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadricula',
            name='DNI',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tiene actualmente DNI'),
        ),
    ]
