# Generated by Django 3.1.7 on 2021-06-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0018_auto_20210615_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadricula',
            name='inconveniente',
            field=models.TextField(blank=True, null=True, verbose_name='Que inconveniente Tiene'),
        ),
    ]
