# Generated by Django 3.1.7 on 2021-06-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0019_auto_20210615_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadricula',
            name='cobertura_de_salud',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tiene Cobertura de salud?'),
        ),
        migrations.AlterField(
            model_name='cuadricula',
            name='cobran_correctamente',
            field=models.BooleanField(blank=True, help_text='¡Cobran las prestaciones de ANSES correctamente?', null=True),
        ),
        migrations.AlterField(
            model_name='cuadricula',
            name='inconveniente',
            field=models.TextField(blank=True, null=True, verbose_name='¿Que inconveniente Tiene?'),
        ),
        migrations.AlterField(
            model_name='cuadricula',
            name='inscriptx_vacuna',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Esta Incriptx a la vacuna contra el COVID-19?'),
        ),
        migrations.AlterField(
            model_name='cuadricula',
            name='mayores',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='¿Cuantos mayores viven en el hogar?'),
        ),
        migrations.AlterField(
            model_name='cuadricula',
            name='menores',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='¿Cuantos menores viven en el hogar?'),
        ),
    ]
