# Generated by Django 3.1.7 on 2021-06-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0024_cuadricula_beneficios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadricula',
            name='mejoras',
            field=models.TextField(blank=True, null=True, verbose_name='¿Qué crees que se puede mejorar del barrio?'),
        ),
        migrations.AddField(
            model_name='cuadricula',
            name='otros',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuadricula',
            name='conoces_la_linea_144',
            field=models.BooleanField(blank=True, help_text='Existe el programa ACOMPAÑAR, el cual buscar fortalecer economicamente a las victimas que sufren violencia de genero', null=True, verbose_name='¿Sabias que en caso de visualizar un caso de violencia de genero podes llamar al 144?'),
        ),
    ]
