# Generated by Django 3.1.7 on 2021-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0025_auto_20210617_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadricula',
            name='politica1',
            field=models.TextField(blank=True, null=True, verbose_name='¿Alguna medida del gobierno le parecio buena? ¿Cuál/es?'),
        ),
        migrations.AddField(
            model_name='cuadricula',
            name='politica2',
            field=models.TextField(blank=True, null=True, verbose_name='¿Alguna medida del gobierno le parecio mala? ¿Cuál/es?'),
        ),
    ]
