# Generated by Django 3.1.7 on 2021-06-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0027_auto_20210617_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadricula',
            name='direccion',
            field=models.CharField(default='calle falsa 232', max_length=60),
            preserve_default=False,
        ),
    ]
