# Generated by Django 3.1.7 on 2021-07-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0028_cuadricula_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadricula',
            name='trabajo_registrado',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tiene trabajo registrado?'),
        ),
    ]
