# Generated by Django 3.1.7 on 2021-07-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0032_auto_20210707_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadricula',
            name='turno',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Necesita un turno por renovacion o por emision de un nuevo ejemplar?'),
        ),
    ]
