# Generated by Django 3.1.7 on 2021-07-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0033_cuadricula_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadricula',
            name='vacunacion',
            field=models.CharField(blank=True, choices=[('0', 'NO'), ('1', 'Si, con la Primera dosis'), ('2', 'Si, con la Segunda dosis')], max_length=1, null=True),
        ),
    ]
