# Generated by Django 3.1.7 on 2021-07-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0034_cuadricula_vacunacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituciones',
            name='geo_parcial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='instituciones',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituciones',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
