# Generated by Django 3.1.7 on 2021-07-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0035_auto_20210712_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituciones',
            name='geo_parcial',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Geolocalizado'),
        ),
    ]
