# Generated by Django 3.1.7 on 2021-08-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0036_auto_20210731_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades_basicas',
            name='geo_parcial',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Geolocalizado'),
        ),
        migrations.AddField(
            model_name='unidades_basicas',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidades_basicas',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
