# Generated by Django 3.1.7 on 2021-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0037_auto_20210803_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades_basicas',
            name='barrio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidades_basicas',
            name='casa_operativa',
            field=models.FloatField(blank=True, default=False, null=True),
        ),
    ]
