# Generated by Django 3.1.7 on 2021-08-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0038_auto_20210823_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades_basicas',
            name='casa_operativa',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
