# Generated by Django 3.1.7 on 2021-11-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0021_auto_20210614_1414'),
        ('territorio', '0040_cuadricula_caso_de_gestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='compañerxs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('trabaja_en_el_estado', models.BooleanField(blank=True, default=False, null=True)),
                ('barrio', models.CharField(blank=True, max_length=50, null=True)),
                ('afiliado_al_pj', models.BooleanField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('geo_parcial', models.BooleanField(blank=True, default=False, null=True, verbose_name='Geolocalizado')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prestadores.localidad')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='territorio.organizacion')),
            ],
            options={
                'verbose_name': 'Unidad Basica',
                'verbose_name_plural': 'Unidad Basica',
            },
        ),
    ]
