# Generated by Django 3.1.7 on 2021-11-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0041_compañerxs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compañerxs',
            options={'verbose_name': 'compañerx', 'verbose_name_plural': 'Compañerxs'},
        ),
        migrations.AlterField(
            model_name='compañerxs',
            name='afiliado_al_pj',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
