# Generated by Django 3.1.7 on 2021-07-30 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestadores', '0021_auto_20210614_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefonos', models.TextField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('subdirector', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('geo_parcial', models.BooleanField(blank=True, default=False, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.localidad')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.municipio')),
            ],
            options={
                'verbose_name': 'Clinica',
                'verbose_name_plural': 'Clinicas',
            },
        ),
    ]
