# Generated by Django 3.1.7 on 2021-07-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadores',
            name='geo_parcial',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Geolocalizado'),
        ),
    ]
