# Generated by Django 3.1.7 on 2021-07-31 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0021_auto_20210614_1414'),
        ('ioma', '0002_auto_20210731_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='postas_itinerantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_de_vacunados', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.localidad')),
            ],
            options={
                'verbose_name': 'Opetativo',
                'verbose_name_plural': 'Operativos',
            },
        ),
    ]
