# Generated by Django 3.1.7 on 2021-07-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioma', '0003_postas_itinerantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postas_itinerantes',
            name='cantidad_de_vacunados',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
