# Generated by Django 3.1.7 on 2021-08-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0021_auto_20210614_1414'),
        ('ioma', '0004_auto_20210731_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='postas_ioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, choices=[('FIJA', 'FIJA'), ('INTI', 'ITINERANTE')], max_length=4, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_de_vacunados', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.DateField(blank=True)),
                ('fecha_fin', models.DateField(blank=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.localidad')),
            ],
            options={
                'verbose_name': 'Opetativo',
                'verbose_name_plural': 'Operativos',
            },
        ),
        migrations.DeleteModel(
            name='postas_itinerantes',
        ),
    ]
