# Generated by Django 3.1.7 on 2021-08-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0021_auto_20210614_1414'),
        ('ioma', '0005_auto_20210804_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postas_ioma',
            new_name='postas_itinerantes',
        ),
    ]
