# Generated by Django 3.1.7 on 2021-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioma', '0006_auto_20210804_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='afiliados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_y_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_de_afiliado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_de_nacimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('localidades', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
            },
        ),
    ]
