# Generated by Django 3.1.7 on 2021-04-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0003_auto_20210421_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidios',
            old_name='descipcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='centros',
            name='personeria_Juridica',
            field=models.CharField(blank=True, choices=[('R', 'Regularizar/Normalizar'), ('C', 'Construir'), ('T', 'En Tramite'), ('N', 'No Tiene')], max_length=1, null=True),
        ),
    ]
