# Generated by Django 3.1.7 on 2021-04-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0004_auto_20210421_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centros',
            name='personeria_Juridica',
            field=models.CharField(blank=True, choices=[('R', 'Regularizar/Normalizar'), ('C', 'Construir'), ('T', 'En Tramite'), ('N', 'No Tiene'), ('B', 'En Regla')], max_length=1, null=True),
        ),
    ]
