# Generated by Django 3.1.7 on 2021-10-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones_civiles', '0002_auto_20211002_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociaciones_civiles',
            name='grado_de_relacion',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True),
        ),
    ]
