# Generated by Django 3.1.7 on 2021-10-02 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones_civiles', '0003_auto_20211002_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociaciones_civiles',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asociaciones_civiles.proceso'),
        ),
        migrations.AlterField(
            model_name='asociaciones_civiles',
            name='situacion_documental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asociaciones_civiles.situacion_documental'),
        ),
    ]
