# Generated by Django 3.1.7 on 2021-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones_civiles', '0004_auto_20211002_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociaciones_civiles',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
