# Generated by Django 3.1.7 on 2021-06-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos_de_gestion', '0008_auto_20210608_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='casos_de_gestion.organismo')),
            ],
            options={
                'verbose_name': 'Informes de gestion',
                'verbose_name_plural': 'Informes de gestion',
            },
        ),
    ]
