# Generated by Django 3.1.7 on 2021-06-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informes',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
