# Generated by Django 3.1.7 on 2021-06-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_informes_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informes',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
