# Generated by Django 3.1.7 on 2021-04-06 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestadores', '0012_resonancia_magnetica_tomografia_computada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion_de_primer_nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencion', models.CharField(choices=[('MM', 'MUY MALA'), ('M', 'MALA'), ('B', 'BUENA'), ('MB', 'MUY BUENA')], max_length=2)),
                ('afiliado', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_del_reclamo', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestadores.agencia')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestadores.prestadoresdeprimernivel')),
            ],
            options={
                'verbose_name': 'Atencion de primer Nivel',
                'verbose_name_plural': 'Atencion de primer Nivel',
            },
        ),
    ]
