# Generated by Django 3.1.7 on 2021-09-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='casos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.CharField(blank=True, max_length=15, null=True)),
                ('cedula', models.CharField(blank=True, max_length=15, null=True)),
                ('nacionalidad', models.CharField(blank=True, choices=[('PAR', 'PARAGUYO/A'), ('BOL', 'BOLIVIANO/A'), ('URU', 'URUGUAYO/A'), ('BRA', 'BRASILENO/A'), ('CHI', 'CHILENO/A')], max_length=3, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('expediente', models.CharField(blank=True, max_length=25, null=True)),
                ('contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('fecha_de_entrada', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('geo_parcial', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
