# Generated by Django 3.1.7 on 2021-09-23 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0021_auto_20210614_1414'),
        ('migraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CasosMigraciones', to='prestadores.localidad'),
        ),
    ]
