# Generated by Django 3.1.7 on 2021-09-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migraciones', '0002_casos_localidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casos',
            old_name='domicilio',
            new_name='direccion',
        ),
    ]
