# Generated by Django 3.1.7 on 2021-11-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migraciones', '0004_auto_20211031_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casos',
            options={'verbose_name': 'Caso', 'verbose_name_plural': 'Casos'},
        ),
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'verbose_name': 'Nacionalidad', 'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='cedula',
            new_name='dni_cedula',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='fecha_de_entrada',
            new_name='fecha_de_nacimiento',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='dni',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='estado',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='contacto',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='casos',
            name='agente',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='casos',
            name='estado_del_tramite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='casos',
            name='fecha_de_toma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casos',
            name='lugar_de_toma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='casos',
            name='modo_de_toma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
