# Generated by Django 3.1.7 on 2022-03-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migraciones', '0006_auto_20220329_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='interministerial',
            field=models.BooleanField(default=False),
        ),
    ]
