# Generated by Django 3.1.7 on 2022-09-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0002_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Direccion',
            field=models.CharField(default='cha', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='plenario',
            field=models.CharField(choices=[('LAF', 'G. de Laferrere'), ('CAS', 'I. Casanova'), ('CAT', 'G. Catan')], default='LAF', max_length=3),
            preserve_default=False,
        ),
    ]
