# Generated by Django 3.1.7 on 2022-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0003_auto_20220905_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='plenario',
            field=models.CharField(choices=[('LAF', 'G. de Laferrere'), ('MAD', 'V. Madero'), ('CAS', 'I. Casanova'), ('CAT', 'G. Catan')], max_length=3),
        ),
    ]
