# Generated by Django 3.1.7 on 2022-09-06 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0021_auto_20210614_1414'),
        ('Formulario', '0006_auto_20220905_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='localidad',
            field=models.ForeignKey(help_text=' (¿Donde vivis?)', on_delete=django.db.models.deletion.PROTECT, to='prestadores.localidad'),
        ),
    ]
