# Generated by Django 3.1.7 on 2022-09-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0008_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='localidad',
            field=models.ForeignKey(help_text=' (¿Donde vivis?)', on_delete=django.db.models.deletion.PROTECT, to='Formulario.localidad'),
        ),
    ]
