# Generated by Django 3.1.7 on 2021-04-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geriatrico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geriatrico',
            name='tipo',
            field=models.CharField(choices=[('E', 'RAM'), ('N', 'RAMP'), ('C', 'CENTRO DE DIA')], max_length=1),
        ),
    ]
