# Generated by Django 3.1.7 on 2021-04-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geriatrico', '0003_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='geriatrico',
            name='CUIT',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
