# Generated by Django 3.1.7 on 2021-04-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geriatrico', '0004_geriatrico_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='tipo',
            field=models.CharField(choices=[('E', 'RAM'), ('N', 'RAMP'), ('C', 'CENTRO DE DIA')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geriatrico',
            name='tipo',
            field=models.CharField(blank=True, choices=[('E', 'RAM'), ('N', 'RAMP'), ('C', 'CENTRO DE DIA')], max_length=1, null=True),
        ),
    ]
