# Generated by Django 3.1.7 on 2021-04-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geriatrico', '0005_auto_20210420_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='geriatrico',
            name='sap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
