# Generated by Django 3.1.7 on 2021-03-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localidad',
            old_name='departamento',
            new_name='municipio',
        ),
    ]
