# Generated by Django 3.1.7 on 2021-03-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0002_auto_20210329_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestadoresdeprimernivel',
            options={'verbose_name': 'Prestador de Primer Nivel', 'verbose_name_plural': 'Prestadores de Primer Nivel'},
        ),
        migrations.AddField(
            model_name='prestadoresdeprimernivel',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prestadoresdeprimernivel',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
