# Generated by Django 3.1.7 on 2021-04-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0007_auto_20210331_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadoresdeprimernivel',
            name='oficina',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='prestadoresdeprimernivel',
            name='piso',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
