# Generated by Django 3.1.7 on 2021-04-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0008_auto_20210401_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadoresdesegundonivel',
            name='capita',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
