# Generated by Django 3.1.7 on 2021-04-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0009_prestadoresdesegundonivel_capita'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadoresdeprimernivel',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
