# Generated by Django 3.1.7 on 2021-04-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0014_procedimientos_neurologicos_pe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Odontologia_alto_riezgo',
            new_name='Odontologia_alto_riesgo',
        ),
        migrations.AlterModelOptions(
            name='odontologia_alto_riesgo',
            options={'verbose_name': 'Odontologia alto riesgo', 'verbose_name_plural': 'Odontologia alto riesgo'},
        ),
    ]
