# Generated by Django 3.1.7 on 2021-04-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0016_direcciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestadoresdesegundonivel',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='prestadoresdesegundonivel',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='prestadoresdesegundonivel',
            name='municipio',
        ),
        migrations.AddField(
            model_name='direcciones',
            name='razon_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.prestadoresdesegundonivel'),
        ),
    ]
