# Generated by Django 3.1.7 on 2021-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0019_comentariosresonancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologia_alto_riesgo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odontologia_primaria',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odontologia_servicios_complementarios',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oftalmologia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
