# Generated by Django 3.1.7 on 2021-06-07 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestadores', '0019_comentariosresonancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
            },
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('metodo_de_entrada', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_de_Tramite', models.CharField(blank=True, max_length=5, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_de_entrada', models.DateField(blank=True, null=True)),
                ('fecha_de_resolucion', models.DateField(blank=True, null=True)),
                ('persona_de_Seguimiento', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_de_seguimiento', models.DateField(blank=True, null=True)),
                ('fecha_de_2ndo_Seguimiento', models.DateField(blank=True, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestadores.localidad')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casos_de_gestion.organismo')),
            ],
            options={
                'verbose_name': 'Casos de gestion',
                'verbose_name_plural': 'Casos de gestion',
            },
        ),
    ]
