# Generated by Django 3.1.7 on 2021-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0002_casos_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Region',
            },
        ),
           ]
