# Generated by Django 3.1.7 on 2021-06-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0003_auto_20210607_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismo',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organismo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
