# Generated by Django 3.1.7 on 2021-06-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0019_comentariosresonancia'),
        ('casos_de_gestion', '0004_auto_20210607_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prestadores.localidad'),
        ),
        migrations.AlterField(
            model_name='casos',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='casos_de_gestion.organismo'),
        ),
        migrations.AlterField(
            model_name='casos',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='casos_de_gestion.region'),
        ),
    ]
