# Generated by Django 3.1.7 on 2021-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0006_auto_20210607_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='caso_resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
