# Generated by Django 3.1.7 on 2021-06-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0008_auto_20210608_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casos',
            name='fecha_de_2ndo_Seguimiento',
        ),
        migrations.RemoveField(
            model_name='casos',
            name='fecha_de_seguimiento',
        ),
        migrations.AlterField(
            model_name='casos',
            name='persona_de_Seguimiento',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
