# Generated by Django 3.1.7 on 2021-06-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0009_auto_20210616_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='organizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='casos',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
