# Generated by Django 3.1.7 on 2021-06-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0010_auto_20210625_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casos',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
