# Generated by Django 3.1.7 on 2021-08-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0012_casos_geo_parcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='interministerial',
            field=models.BooleanField(default=False),
        ),
    ]
