# Generated by Django 3.1.7 on 2021-10-22 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0014_auto_20210907_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='organismo',
            field=models.ForeignKey(default='16', on_delete=django.db.models.deletion.PROTECT, to='casos_de_gestion.organismo'),
            preserve_default=False,
        ),
    ]
