# Generated by Django 3.1.7 on 2021-10-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_agenda_localidad'),
        ('casos_de_gestion', '0015_auto_20211021_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='lugar_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.agenda'),
        ),
    ]
