# Generated by Django 3.1.7 on 2021-10-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_auto_20211028_1259'),
        ('casos_de_gestion', '0017_auto_20211028_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='lugar_operativo',
            field=models.ForeignKey(blank=True, db_column='lugar', null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.agenda', to_field='lugar'),
        ),
    ]
