# Generated by Django 3.1.7 on 2021-10-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0018_auto_20211028_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='metodo_de_entrada',
            field=models.CharField(default='01/01/2021', max_length=30),
            preserve_default=False,
        ),
    ]
