# Generated by Django 3.1.7 on 2021-11-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0020_auto_20211029_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casos_interminitserial',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('casos_de_gestion.casos',),
        ),
    ]
