# Generated by Django 3.1.7 on 2021-11-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_agenda_vigente'),
        ('casos_de_gestion', '0021_casos_interminitserial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='lugar_operativo',
            field=models.ForeignKey(blank=True, db_column='lugar', limit_choices_to={'vigente': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.agenda', to_field='lugar'),
        ),
    ]
