# Generated by Django 3.1.7 on 2021-11-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_agenda_vigente'),
        ('casos_de_gestion', '0022_auto_20211104_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='lugar_operativo',
            field=models.ForeignKey(db_column='lugar', default='No Aplica', limit_choices_to={'vigente': True}, on_delete=django.db.models.deletion.PROTECT, to='agenda.agenda', to_field='lugar'),
            preserve_default=False,
        ),
    ]
