# Generated by Django 3.1.7 on 2021-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0023_auto_20211111_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='domicilio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
