# Generated by Django 3.1.7 on 2021-11-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0024_auto_20211111_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casos_interminitserial',
            options={'verbose_name': 'Casos de Interministeriles', 'verbose_name_plural': 'Casos de Interministeriales'},
        ),
    ]
