# Generated by Django 3.1.7 on 2022-07-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_gestion', '0026_auto_20220711_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='fecha_de_entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
