# Generated by Django 3.1.7 on 2021-10-22 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('socio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_aviso', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_aviso', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_inicio', models.DateField(blank=True, null=True)),
                ('fecha_de_fin', models.DateField(blank=True, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('medio_de_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cronos.modalidad')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cronos.cliente')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
    ]
