# Generated by Django 3.1.7 on 2021-10-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronos', '0002_aranceles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
