# Generated by Django 3.1.7 on 2021-10-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronos', '0003_auto_20211021_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
