# Generated by Django 3.1.7 on 2021-10-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronos', '0004_auto_20211021_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='mediodepago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de pago',
            },
        ),
    ]
