# Generated by Django 3.1.7 on 2021-10-22 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cronos', '0005_mediodepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='nombre',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='medio_de_pago',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='cronos.mediodepago'),
            preserve_default=False,
        ),
    ]
