# Generated by Django 3.1.7 on 2021-10-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronos', '0006_auto_20211022_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
