# Generated by Django 3.1.7 on 2021-10-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronos', '0007_cliente_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
