# Generated by Django 3.1.7 on 2021-11-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronos', '0008_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='peso_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
